### ISSUE TITLE
[Feature request] Cloud mode for FB pixel 

### ISSUE THREAD

**Issue by Sshuichi** [rudderlabs/rudder-server#349]
Since rudderstack aims to be the one SDK that rules them all, and since performance is hindered by so many SDKs such us GA, FB pixel, etc.. 
I would like to ask to add the cloud support of the FB pixel so we don't have to load it in the DOM 
Here is the documentation of server API 
https://developers.facebook.com/docs/marketing-api/server-side-api/using-the-api/

Thank you!

**Comment by arnabp92** [comment]
@Sshuichi Will look into it!

**Comment by Sshuichi** [comment]
Hey @arnabp92, did this make it to the prioritization? :)

**Comment by arnab-p** [comment]
@Sshuichi we couldn't take it to the priority yet. We'll try to take it in priority in the next 2-3 weeks.

**Comment by Sshuichi** [comment]
Hey @arnab-p. Hopefully it made it to the priority list?

**Comment by BlakeBeus** [comment]
@arnab-p just checking in on this.

Facebook has changed the name of their ad conversion API. It's no longer the server API but the Conversations API.

Better conversion attribution is a huge demand issue right now for companies spending money on ads. The FB pixel is very inaccurate and now that iOS 14 is rolling out it's going to be worse.

I think there's a big opportunity to get market share because not many providers are integrating with the Conversations API.

https://developers.facebook.com/docs/marketing-api/conversions-api/

I'd love to see this in there! Thanks for the awesome product!

**Comment by Sshuichi** [comment]
It was released @BlakeBeus, but needs some transformations to ignore the page views that generate some noise. 
You can just add FB pixel and toggle off use native SDK

**Comment by cisse21** [comment]
https://docs.rudderstack.com/destinations/advertising/fb-pixel

The support was added for this. Please refer to the docs for more information.
